name: Deploy to Pi
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: |
        docker build -t weather-bro-app:latest .
        docker stop weather-bro-app || true && docker rm weather-bro-app || true
        docker run -d --name weather-bro-app -p 3000:3000 --restart unless-stopped weather-bro-app:latest